// ui/src/features/shell/ProfileSwitcher.tsx
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '../../components/ui/select';
import type { BoardProfile } from '../../lib/api/types';

export function ProfileSwitcher({
  profile,
  profiles,
  onChoose,
}: {
  profile: string | null;
  profiles: BoardProfile[];
  onChoose: (name: string) => void;
}) {
  return (
    <Select value={profile ?? undefined} onValueChange={onChoose}>
      <SelectTrigger className="w-full" aria-label="Profile">
        <SelectValue placeholder="Select profile" />
      </SelectTrigger>
      <SelectContent>
        {profiles.map((p) => (
          <SelectItem key={p.name} value={p.name}>
            {p.name}
            {p.hasDb ? '' : ' (no local db)'}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  );
}

// ui/src/features/shell/ProfileSwitcher.svelte
<script lang="ts">
  import type { BoardProfile } from '../../lib/api/types';

  let {
    profiles,
    current,
    choose,
  }: { profiles: BoardProfile[]; current: string | null; choose: (name: string) => void } =
    $props();
</script>

<label class="profile-switcher">
  <span>Profile</span>
  <select value={current ?? ''} onchange={(e) => choose(e.currentTarget.value)}>
    {#each profiles as p (p.name)}
      <option value={p.name}>{p.name}{p.hasDb ? '' : ' (no local db)'}</option>
    {/each}
  </select>
</label>
